---
apiVersion: v1
kind: Secret
metadata:
  name: frontend114-app-frontend-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/frontend114-app-frontend-gitops
